### ISSUE TITLE
INVALID_CLIENT: invalid redirect URI

### ISSUE THREAD

**Issue by jonajgs** [jeweller1980stepanets/Cordova-spotify-plugin-ios-android#2]
I put the application name, and the package name, but I doesnt work

i put:
my.package.com
my.package.com://callback
myAppName
myAppName://callback

and I added that callbacks uri in my spotify's application

**Comment by jeweller1980stepanets** [comment]
Hi, you must register your application in the Spotify service
![image](https://cloud.githubusercontent.com/assets/17783958/25657544/16ecdf16-3007-11e7-809b-a63348536d8b.png)


![image](https://cloud.githubusercontent.com/assets/17783958/25657467/a8e4e630-3006-11e7-8055-c4a138835544.png)

**Comment by jonajgs** [comment]
i worked, but the app crased hen i am trying to login

**Comment by jeweller1980stepanets** [comment]
Please send me logs or screenshots .... I do not quite understand what the problem is

**Comment by jonajgs** [comment]
I dont know whats wrong, I'm trying to do myself, but, It does not work for me when press the ok button

this
![screenshot at may 08 18-39-33](https://cloud.githubusercontent.com/assets/9200075/25829730/c2d7b8d6-341d-11e7-85ff-df631812e48c.png)

Do not do the redirect, do you know what may be happening?

@jeweller1980stepanets
